### ISSUE TITLE
suppress byline display on everything except news items

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.theme#42]

**Comment by alecpm** [comment]
This should be fixed.  Currently bylines are shown only on News Items unless the user has permission to edit the content being viewed (in which case the byline is shown in order to provide the "History" feature).  I can easily disable that exception if desired though.

**Comment by paregorios** [comment]
This is great!

**Comment by paregorios** [comment]
Reopening: we're still seeing byline on the featured/pinned item on the events listing:

![byline-events](https://cloud.githubusercontent.com/assets/263285/8083622/8720d064-0f4b-11e5-8681-b9a0031dd7bc.jpg)

**Comment by skleinfeldt** [comment]
Guessing that is a special part of the view that needs adjusting - sorry we missed that... Back to you @alecpm

**Comment by alecpm** [comment]
Yes, this is annually coded into the events listing. I can remove it from the template.

**Comment by paregorios** [comment]
Please do rip it out, thanks.

**Comment by alecpm** [comment]
This should be fixed.
